### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by paescuj** [voxpupuli/puppet-rabbitmq#817]
Do you think a new version release would be possible soon?
We are interested particularly in https://github.com/voxpupuli/puppet-rabbitmq/pull/814 since the module is currently not working with RabbitMQ version 3.8.0.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: -
- Distribution: CentOS 7
- Module version: 9.1.0

## How to reproduce (e.g Puppet code you use)

Include module

## What are you seeing

```Failed to apply catalog: undefined method `scan' for nil:NilClass```

## What behaviour did you expect instead

No error

**Comment by KrzysztofHajdamowicz** [comment]
+1

**Comment by s2490** [comment]
+1

**Comment by wyardley** [comment]
Hi y'all

As far as cutting a release that gets out #814, I've done that.
If that doesn't resolve the issue that #819 is trying to fix, may need to do some more adjustments there.

This also contains a second breaking(ish) change, so please read the changelog / release notes.
